### ISSUE TITLE
Swiper / Expander Bug?

### ISSUE THREAD

**Issue by FedgarLurch** [nutteloost/simple-swipe-card#12]
I am going to post this in both places and edit them to link to each other, because I truthfully don't know which thing is interfearing with which.

I have (Or the goal is) to have a swiper card that holds different lists inside of it, that is normally unexpanded. So it shows up narrow with just a list, and then from there when interacted with, expands and I can swipe between my various lists.

Problem is, the swipe function doesn't seem to work nested in there.

Here is the code:
```
type: custom:expander-card
cards:
  - type: custom:simple-swipe-card
    show_pagination: true
    card_spacing: 15
    enable_loopback: true
    swipe_direction: horizontal
    enable_auto_swipe: false
    auto_swipe_interval: 2000
    enable_reset_after: false
    reset_after_timeout: 30000
    reset_target_card: 1
    cards:
      - display_order: duedate_asc
        type: todo-list
        entity: todo.home_improvement
        title: Home Improvement
      - display_order: none
        type: todo-list
        entity: todo.wedding_list
        title: Wedding List
      - display_order: none
        type: todo-list
        entity: todo.groceries
        title: Groceries List
```

Now, the expanding part works fine, the thing that doesn't work is the swiping. See the below photos.

![Image](https://github.com/user-attachments/assets/b80719f3-5956-4ede-986e-79f6112a7dd0)

That is what happens when I try to swipe. There are no console errors and everything has been updated. 
I am happy to help debug, I just don't know where to start. 

Thanks!
