### ISSUE TITLE
[FEATURE REQUEST] More slides per view

### ISSUE THREAD

**Issue by bladecell** [nutteloost/simple-swipe-card#5]
Hey could you add option to add more slides per view, not just one?
Result would be something like this

![Image](https://github.com/user-attachments/assets/c3f98a73-a6d0-4fad-847c-c0e717de7f94)

**Comment by andiohn** [comment]
Ya, that would be great; I'm using layout card to get some more.

**Comment by jjanssen95** [comment]
This would be the dream feature for me! I'm a heavy "swipe-card"  user for this now as my whole (Google home inspired) dashboard relies on this feature. But simple swipe-card is so much better in terms of UI setup! 

For me it's crucial you will be able to see part of the next card so users see they are able to swipe (without adding bullets)

<img width="1170" height="2532" alt="Image" src="https://github.com/user-attachments/assets/40e0a798-3265-40d0-a696-1e4f02ac1676" />

**Comment by bladecell** [comment]
Thanks for adding this, but when I drag multiple slides, it moves the slides only by one. I would like to stay on slides I had swiped to.

![Image](https://github.com/user-attachments/assets/e6f9fd9c-257f-4a82-8468-f09792bf71f0)

**Comment by nutteloost** [comment]
@bladecell, currently that is the correct behaviour. It does move slides one by one. I will add different swipe / scroll behaviours in a later release. Could you send me your card configuration so I can test this during developing?

**Comment by bladecell** [comment]
Yeah, sure, just had to remove the local icons and pirate weather states from the button-card template, but this should work
<details>
  <summary>Swipe card</summary>
 
  ```yaml
  type: custom:simple-swipe-card
    view_mode: carousel
    card_min_width: 60
    card_spacing: 6
    show_pagination: false
    cards:
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 0h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 1h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 2h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 3h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 4h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 5h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 6h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 7h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 8h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 9h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 10h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 11h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 12h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 13h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 14h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 15h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 16h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 17h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 18h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 19h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 20h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 21h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 22h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 23h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 24h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 25h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 26h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 27h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 28h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 29h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 30h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 31h
      - type: custom:button-card
        template: hourly-forecast
        variables:
          h: 32h

  ```
  
</details>

<details>
  <summary>hourly-forecast</summary>

  
  ```yaml
button_card_templates:
    hourly-forecast:
    variables:
      h: 0h
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.popup
        data:
          size: normal
          style: |
            ha-dialog {
              --mdc-dialog-min-height: fit-content !important;
              --mdc-dialog-max-height:  var(--mdc-dialog-min-height) !important;
              --ha-dialog-border-radius: var(--ha-card-border-radius) !important;
              --vertical-align-dialog: center !important;
              --header-height: 5vh !important;
              --footer-height: var(--header-height) !important;
              --padding-y: 8px !important;
              -webkit-tap-highlight-color: rgba(0, 0, 0, 0) !important;
            }
            .content {
              height: fit-content !important;
              max-height: 90vh !important
              pointer-events: unset !important;
              padding: 0 !important;
            }
            .container {
              padding: 0 !important;
            }
          title: |
            [[[ 
              const now = new Date();
              const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
              const hoursToAdd = parseInt(variables.h.replace('h', ''), 10);
              
              if (hoursToAdd === 0) {
                  return `${months[now.getMonth()]} ${now.getDate().toString().padStart(2, '0')} - ${now.getHours().toString().padStart(2, '0')}:00`;
              }
              const futureTime = new Date(now.getTime() + hoursToAdd * 60 * 60 * 1000);
              return `${months[futureTime.getMonth()]} ${futureTime.getDate().toString().padStart(2, '0')} - ${futureTime.getHours().toString().padStart(2, '0')}:00`;
            ]]]
          content:
            type: custom:button-card
            variables:
              h: '[[[ return variables.h ]]]'
            styles:
              grid:
                - grid-template-areas: '"icon current" "icon feels" "icon prec" "icon precprob"'
                - grid-template-columns: 1fr 2fr
                - grid-template-rows: 1fr 1fr 1fr 1fr
              card:
                - border-radius: 30px
                - padding: 20px
                - background: none
              custom_fields:
                icon:
                  - justify-self: center
                prec:
                  - justify-self: start
                  - padding-left: 20px
                precprob:
                  - justify-self: start
                  - padding-left: 20px
                current:
                  - justify-self: start
                  - padding-left: 20px
                feels:
                  - justify-self: start
                  - padding-left: 20px
            custom_fields:
              icon: |
                [[[
                  return  'icon'
                ]]]
              prec: |
                [[[
                  return variables.h + ' mm'
                ]]]
              precprob: |
                [[[
                  return variables.h + ' %'
                ]]]
              current: |
                [[[
                  return variables.h + '°C'
                ]]]
              feels: |
                [[[
                  return variables.h + '°C'
                ]]]
    state:
      - operator: template
        value: |
          [[[ 
            return variables.h == '0'
          ]]]
        styles:
          custom_fields:
            prec:
              - display: none
    styles:
      grid:
        - grid-template-areas: '"temp" "icon" "prec" "time"'
        - grid-template-column: auto
        - grid-template-rows: 1fr 2fr 1fr 1fr
      card:
        - height: 200px
        - width: 60px
        - border-radius: 30px
      custom_fields:
        temp:
          - justify-self: center
          - margin-top: 10px
          - align-content: center
          - background: |
              [[[
                return ((variables.h === '0h') ? 'var(--card-background-gradient)' : 'none')
              ]]]
          - height: 40px
          - width: 40px
          - border-radius: 20px
          - clip-path: >-
              path('M19 0 C24.7 0 30.4 5.7 30.4 11.4 C30.4 17.1 24.7 22.8 19
              22.8 C13.3 22.8 7.6 17.1 7.6 11.4 C7.6 5.7 13.3 0 19 0 M19 38
              C13.3 38 7.6 32.3 7.6 26.6 C7.6 20.9 13.3 15.2 19 15.2 C24.7 15.2
              30.4 20.9 30.4 26.6 C30.4 32.3 24.7 38 19 38 M0 19 C0 13.3 5.7 7.6
              11.4 7.6 C17.1 7.6 22.8 13.3 22.8 19 C22.8 24.7 17.1 30.4 11.4
              30.4 C5.7 30.4 0 24.7 0 19 M38 19 C38 24.7 32.3 30.4 26.6 30.4
              C20.9 30.4 15.2 24.7 15.2 19 C15.2 13.3 20.9 7.6 26.6 7.6 C32.3
              7.6 38 13.3 38 19')
        time:
          - justify-self: center
          - margin-bottom: 15px
        icon:
          - justify-self: center
          - margin-top: 30px
        prec:
          - justify-self: center
          - font-size: 16px
          - font-weight: 300
          - opacity: 0.7
    custom_fields:
      temp: |
        [[[
          return variables.h + '°'
        ]]]
      icon: |
        [[[
          return  'icon'
        ]]]
      time: |
        [[[ 
          const now = new Date();
          const hoursToAdd = parseInt(variables.h.replace('h', ''), 10);
          if (hoursToAdd === 0) {
            return 'Now';
          }
          const futureHour = (now.getHours() + hoursToAdd) % 24;
          return futureHour.toString().padStart(2, '0') + ':00';
        ]]]
      prec: |
        [[[
          return variables.h + '%'
        ]]]
  ```
 
</details>
